<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ63rqic\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ63rqic/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ63rqic.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ63rqic\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ63rqic\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Z63rqic',
    'container.build_id' => '4c264011',
    'container.build_time' => 1528144226,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ63rqic');
